// === CONFIG ===
const API_URL = "https://pathfinder-246290474963.us-central1.run.app/api/generate";

// === Starfield effect ===
function generateStarfield() {
  const field = document.getElementById("starfield");
  if (!field) return;
  for (let i = 0; i < 100; i++) {
    const s = document.createElement("div");
    s.className = "star";
    s.style.left = Math.random() * 100 + "%";
    s.style.top = Math.random() * 100 + "%";
    s.style.animationDelay = Math.random() * 3 + "s";
    field.appendChild(s);
  }
}

// === Navbar scroll effect ===
const navbar = document.getElementById("navbar");
window.addEventListener("scroll", () => {
  navbar.classList.toggle("scrolled", window.scrollY > 50);
});

// === Elements ===
const generateBtn = document.getElementById("generateBtn");
const jobInput = document.getElementById("jobInput");
const compareInput = document.getElementById("compareInput");
const compareBtn = document.getElementById("compareBtn");
const loader = document.getElementById("loader");
const results = document.getElementById("results");
const demoOutput = document.getElementById("demoOutput");
const skillsGrid = document.getElementById("skillsGrid");
const courseList = document.getElementById("courseList");
const durationValue = document.getElementById("durationValue");
const salaryValue = document.getElementById("salaryValue");
const downloadBtn = document.getElementById("downloadBtn");
const compareSection = document.getElementById("compareResults");
const compareTable = document.getElementById("compareTable");

// === Helper ===
function showLoader(show) {
  loader.style.display = show ? "block" : "none";
}

function cleanJsonString(text) {
  if (!text) return "{}";
  return text.replace(/```json|```/g, "").trim();
}

async function fetchRoadmap(role) {
  const res = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ job_title: role })
  });
  const data = await res.json();
  if (data.ai_text) {
    try {
      return JSON.parse(cleanJsonString(data.ai_text));
    } catch (e) {
      console.warn("Could not parse AI JSON; returning as description only", e);
      return { description: data.ai_text };
    }
  }
  return data;
}

// === Generate single roadmap ===
async function generateRoadmap() {
  const role = jobInput.value.trim();
  if (!role) {
    alert("Please enter a job title!");
    return;
  }
  // Hide compare section
  compareSection.style.display = "none";

  demoOutput.classList.add("visible");
  showLoader(true);
  results.style.display = "none";
  generateBtn.disabled = true;
  generateBtn.textContent = "Generating…";

  try {
    const data = await fetchRoadmap(role);
    populateResults(data, role);
  } catch (err) {
    console.error("Error fetching roadmap:", err);
    alert("Something went wrong. Please try again later.");
  } finally {
    showLoader(false);
    generateBtn.disabled = false;
    generateBtn.textContent = "Generate My Roadmap";
  }
}

// === Populate results for single role ===
function populateResults(data, role) {
  results.style.display = "block";
  skillsGrid.innerHTML = "";
  courseList.innerHTML = "";

  const skills = data.skills || [];
  const courses = data.courses || [];

  if (skills.length) {
    skills.forEach(s => {
      const chip = document.createElement("div");
      chip.className = "skill-chip";
      chip.textContent = s;
      skillsGrid.appendChild(chip);
    });
  } else {
    skillsGrid.innerHTML = "<p style='color:#aaa;'>No skills data found.</p>";
  }

  if (courses.length) {
    courses.forEach(c => {
      const item = document.createElement("div");
      item.className = "course-item";
      item.innerHTML = `<a href="${c.url}" target="_blank">${c.title}</a>`;
      courseList.appendChild(item);
    });
  } else {
    courseList.innerHTML = "<p style='color:#aaa;'>No courses data found.</p>";
  }

  durationValue.textContent = data.duration_months
    ? `${data.duration_months} months`
    : "N/A";
  salaryValue.textContent = data.avg_salary_usd || "N/A";

  downloadBtn.onclick = () => downloadRoadmap(role, data);
}

// === Download roadmap as .txt ===
function downloadRoadmap(role, data) {
  const content = `
PathFinder AI - Career Roadmap
==============================

Role: ${role}

Top Skills:
${(data.skills || []).map((s,i) => `${i+1}. ${s}`).join("\n")}

Recommended Courses:
${(data.courses || [])
    .map((c,i) => `${i+1}. ${c.title}\n   ${c.url}`)
    .join("\n\n")}

Duration: ${data.duration_months || "N/A"} months
Avg Salary: ${data.avg_salary_usd || "N/A"}

Generated by PathFinder AI
  `.trim();

  const blob = new Blob([content], { type: "text/plain" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${role.replace(/\s+/g, "_")}_Roadmap.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

// === Compare two roles ===
async function compareRoadmaps() {
  const role1 = jobInput.value.trim();
  const role2 = compareInput.value.trim();
  if (!role1 || !role2) {
    alert("Please enter both roles to compare!");
    return;
  }
  // Hide single results while comparing
  results.style.display = "none";

  showLoader(true);
  compareBtn.disabled = true;
  compareBtn.textContent = "Comparing…";

  try {
    const [data1, data2] = await Promise.all([
      fetchRoadmap(role1),
      fetchRoadmap(role2)
    ]);
    populateComparison(role1, data1, role2, data2);
  } catch (err) {
    console.error("Error comparing:", err);
    alert("Comparison failed. Please try again.");
  } finally {
    showLoader(false);
    compareBtn.disabled = false;
    compareBtn.textContent = "Compare Roles";
  }
}

// === Populate comparison table ===
function populateComparison(role1, data1, role2, data2) {
  compareSection.style.display = "block";

  const skills1 = data1.skills || [];
  const skills2 = data2.skills || [];
  const common = skills1.filter(s => skills2.includes(s));
  const unique1 = skills1.filter(s => !skills2.includes(s));
  const unique2 = skills2.filter(s => !skills1.includes(s));

  compareTable.innerHTML = `
    <thead>
      <tr><th>Aspect</th><th>${role1}</th><th>${role2}</th></tr>
    </thead>
    <tbody>
      <tr><td>Common Skills</td><td colspan="2">${common.join(", ") || "None"}</td></tr>
      <tr><td>Unique Skills</td><td>${unique1.join(", ") || "None"}</td><td>${unique2.join(", ") || "None"}</td></tr>
      <tr><td>Avg Salary</td><td>${data1.avg_salary_usd || "N/A"}</td><td>${data2.avg_salary_usd || "N/A"}</td></tr>
      <tr><td>Duration</td><td>${data1.duration_months || "N/A"} months</td><td>${data2.duration_months || "N/A"} months</td></tr>
    </tbody>
  `;
}

// === Event listeners ===
generateBtn.addEventListener("click", generateRoadmap);
jobInput.addEventListener("keypress", e => { if (e.key === "Enter") generateRoadmap(); });
compareBtn.addEventListener("click", compareRoadmaps);
compareInput.addEventListener("keypress", e => { if (e.key === "Enter") compareRoadmaps(); });

generateStarfield();

// ============= Compare Roles Logic =============
const compareBtn = document.getElementById("compareBtn");
const compareLoader = document.getElementById("compareLoader");
const compareResults = document.getElementById("compareResults");
const compareError = document.getElementById("compareError");
const compareTableBody = document.getElementById("compareTableBody");

compareBtn?.addEventListener("click", async () => {
  const roleA = document.getElementById("roleA").value.trim();
  const roleB = document.getElementById("roleB").value.trim();
  compareError.style.display = "none";
  compareResults.style.display = "none";

  if (!roleA || !roleB) {
    compareError.textContent = "Please enter both roles.";
    compareError.style.display = "block";
    return;
  }

  compareLoader.style.display = "block";

  try {
    const resp = await fetch("https://pathfinder-246290474963.us-central1.run.app/api/compare", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ role_a: roleA, role_b: roleB }),
    });

    if (!resp.ok) throw new Error("Failed to fetch comparison.");

    const data = await resp.json();
    compareLoader.style.display = "none";
    compareResults.style.display = "block";

    // Fill comparison table
    compareTableBody.innerHTML = "";
    if (data.table && data.table.length > 0) {
      data.table.forEach((row) => {
        const tr = document.createElement("tr");
        tr.innerHTML = `
          <td style="padding:8px;">${row.metric}</td>
          <td style="padding:8px;">${row.roleA}</td>
          <td style="padding:8px;">${row.roleB}</td>
        `;
        compareTableBody.appendChild(tr);
      });
    }

    // Add AI suggestions
    let insightsHTML = "";
    if (data.suggestions && data.suggestions.length > 0) {
      insightsHTML = `
        <div class="glass-card">
          <h3>💡 Gemini Insights</h3>
          <ul style="list-style:disc; margin-left:1.5rem;">
            ${data.suggestions.map((tip) => `<li>${tip}</li>`).join("")}
          </ul>
        </div>
      `;
    }

    // Skills overlap and unique (optional display)
    if (data.skills_overlap) {
      insightsHTML += `
        <div class="glass-card">
          <h3>Skills Comparison</h3>
          <p><strong>Overlap:</strong> ${data.skills_overlap.join(", ")}</p>
          <p><strong>Unique to ${roleA}:</strong> ${data.unique_a.join(", ")}</p>
          <p><strong>Unique to ${roleB}:</strong> ${data.unique_b.join(", ")}</p>
        </div>
      `;
    }

    compareResults.insertAdjacentHTML("beforeend", insightsHTML);
  } catch (err) {
    compareLoader.style.display = "none";
    compareError.textContent = "AI comparison failed. Try again.";
    compareError.style.display = "block";
    console.error(err);
  }
});
