// === CONFIG ===
const API_URL = "https://pathfinder-246290474963.us-central1.run.app/api/generate";
const API_BASE = "https://pathfinder-246290474963.us-central1.run.app";

// === Starfield effect ===
function generateStarfield() {
  const field = document.getElementById("starfield");
  if (!field) return;
  for (let i = 0; i < 100; i++) {
    const s = document.createElement("div");
    s.className = "star";
    s.style.left = Math.random() * 100 + "%";
    s.style.top = Math.random() * 100 + "%";
    s.style.animationDelay = Math.random() * 3 + "s";
    field.appendChild(s);
  }
}

// === Navbar scroll effect ===
const navbar = document.getElementById("navbar");
window.addEventListener("scroll", () => {
  navbar.classList.toggle("scrolled", window.scrollY > 50);
});

// === Elements ===
const generateBtn = document.getElementById("generateBtn");
const jobInput = document.getElementById("jobInput");
const loader = document.getElementById("loader");
const results = document.getElementById("results");
const demoOutput = document.getElementById("demoOutput");
const skillsGrid = document.getElementById("skillsGrid");
const courseList = document.getElementById("courseList");
const durationValue = document.getElementById("durationValue");
const salaryValue = document.getElementById("salaryValue");
const downloadBtn = document.getElementById("downloadBtn");
const compareSection = document.getElementById("compareResults");

// === Helper ===
function showLoader(show) {
  loader.style.display = show ? "block" : "none";
}

// --- Improved JSON extraction ---
function tryExtractJson(text) {
  if (!text) return null;
  const stripped = text.replace(/```json|```/g, "").trim();
  try {
    return JSON.parse(stripped);
  } catch {}
  const start = stripped.indexOf("{");
  const end = stripped.lastIndexOf("}");
  if (start !== -1 && end !== -1 && end > start) {
    const maybe = stripped.slice(start, end + 1);
    try {
      return JSON.parse(maybe);
    } catch {}
  }
  return null;
}

// === Fetch roadmap ===
async function fetchRoadmap(role) {
  const res = await fetch(API_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ job_title: role }),
  });
  const data = await res.json();

  if (data.ai_text) {
    const parsed = tryExtractJson(data.ai_text);
    if (parsed) return parsed;
    return { description: data.ai_text };
  }
  return data;
}

// === Generate single roadmap ===
async function generateRoadmap() {
  const role = jobInput.value.trim();
  if (!role) {
    alert("Please enter a job title!");
    return;
  }

  compareSection.style.display = "none";
  demoOutput.classList.add("visible");
  showLoader(true);
  results.style.display = "none";
  generateBtn.disabled = true;
  generateBtn.textContent = "Generating…";

  try {
    const data = await fetchRoadmap(role);
    populateResults(data, role);
  } catch (err) {
    console.error("Error fetching roadmap:", err);
    alert("Something went wrong. Please try again later.");
  } finally {
    showLoader(false);
    generateBtn.disabled = false;
    generateBtn.textContent = "Generate My Roadmap";
  }
}

// === Populate roadmap results ===
function populateResults(data, role) {
  results.style.display = "block";
  skillsGrid.innerHTML = "";
  courseList.innerHTML = "";

  const skills = data.skills || [];
  const courses = data.courses || [];

  if (skills.length) {
    skills.forEach((s) => {
      const chip = document.createElement("div");
      chip.className = "skill-chip";
      chip.textContent = s;
      skillsGrid.appendChild(chip);
    });
  } else {
    skillsGrid.innerHTML = "<p style='color:#aaa;'>No skills data found.</p>";
  }

  if (courses.length) {
    courses.forEach((c) => {
      const item = document.createElement("div");
      item.className = "course-item";
      item.innerHTML = `<a href="${c.url}" target="_blank">${c.title}</a>`;
      courseList.appendChild(item);
    });
  } else {
    courseList.innerHTML = "<p style='color:#aaa;'>No courses data found.</p>";
  }

  durationValue.textContent = data.duration_months
    ? `${data.duration_months} months`
    : "N/A";
  salaryValue.textContent = data.avg_salary_usd || "N/A";

  downloadBtn.onclick = () => downloadRoadmap(role, data);
}

// === Download roadmap ===
function downloadRoadmap(role, data) {
  const content = `
PathFinder AI - Career Roadmap
==============================

Role: ${role}

Top Skills:
${(data.skills || []).map((s, i) => `${i + 1}. ${s}`).join("\n")}

Recommended Courses:
${(data.courses || [])
    .map((c, i) => `${i + 1}. ${c.title}\n   ${c.url}`)
    .join("\n\n")}

Duration: ${data.duration_months || "N/A"} months
Avg Salary: ${data.avg_salary_usd || "N/A"}

Generated by PathFinder AI
`.trim();

  const blob = new Blob([content], { type: "text/plain" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${role.replace(/\s+/g, "_")}_Roadmap.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

// === Compare Roles Logic ===
async function compareRoles(roleA, roleB) {
  const r = await fetch(`${API_BASE}/api/compare`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ role_a: roleA, role_b: roleB }),
  });
  if (!r.ok) throw new Error(await r.text());
  return r.json();
}

document.getElementById("compareBtn")?.addEventListener("click", async () => {
  const roleA = document.getElementById("roleA").value.trim();
  const roleB = document.getElementById("roleB").value.trim();
  const err = document.getElementById("compareError");
  const loader = document.getElementById("compareLoader");
  const out = document.getElementById("compareResults");
  const tbody = document.getElementById("compareTableBody");

  err.style.display = "none";
  out.style.display = "none";

  if (!roleA || !roleB) {
    err.textContent = "Please enter both roles.";
    err.style.display = "block";
    return;
  }

  loader.style.display = "block";
  try {
    const data = await compareRoles(roleA, roleB);
    loader.style.display = "none";
    out.style.display = "block";

    let payload = data;
    if (data.ai_text) {
      try {
        payload = JSON.parse(data.ai_text);
      } catch {}
    }

    document.getElementById("roleA_th").textContent = roleA || "Role A";
    document.getElementById("roleB_th").textContent = roleB || "Role B";

    tbody.innerHTML = "";
    (payload.table || []).forEach((row) => {
      const tr = document.createElement("tr");
      tr.innerHTML = `
        <td style="padding:8px;">${row.metric ?? ""}</td>
        <td style="padding:8px;">${row.a ?? row.roleA ?? row.role_a ?? ""}</td>
        <td style="padding:8px;">${row.b ?? row.roleB ?? row.role_b ?? ""}</td>
      `;
      tbody.appendChild(tr);
    });

    // Optional skill chips
    const chip = (s) => `<div class="skill-chip">${s}</div>`;
    const overlap = document.getElementById("skillsOverlap");
    const onlyA = document.getElementById("skillsOnlyA");
    const onlyB = document.getElementById("skillsOnlyB");

    if (overlap) overlap.innerHTML = (payload.skills_overlap || []).map(chip).join("");
    if (onlyA) onlyA.innerHTML = (payload.unique_a || []).map(chip).join("");
    if (onlyB) onlyB.innerHTML = (payload.unique_b || []).map(chip).join("");

  } catch (e) {
    loader.style.display = "none";
    err.textContent = `Compare failed: ${e.message}`;
    err.style.display = "block";
    console.error(e);
  }
});

// === Event Listeners ===
generateBtn.addEventListener("click", generateRoadmap);
jobInput.addEventListener("keypress", (e) => {
  if (e.key === "Enter") generateRoadmap();
});

generateStarfield();
