const API_URL = "https://pathfinder-246290474963.us-central1.run.app/api/generate";

const generateBtn = document.getElementById("generateBtn");
const jobInput = document.getElementById("jobInput");
const loader = document.getElementById("loader");
const results = document.getElementById("results");
const demoOutput = document.getElementById("demoOutput");
const skillsGrid = document.getElementById("skillsGrid");
const courseList = document.getElementById("courseList");
const durationValue = document.getElementById("durationValue");
const salaryValue = document.getElementById("salaryValue");
const downloadBtn = document.getElementById("downloadBtn");

function showLoader(show) {
  loader.style.display = show ? "block" : "none";
}

function generateStarfield() {
  const field = document.getElementById("starfield");
  for (let i = 0; i < 100; i++) {
    const s = document.createElement("div");
    s.className = "star";
    s.style.left = Math.random() * 100 + "%";
    s.style.top = Math.random() * 100 + "%";
    s.style.animationDelay = Math.random() * 3 + "s";
    field.appendChild(s);
  }
}

async function generateRoadmap() {
  const job = jobInput.value.trim();
  if (!job) return alert("Enter a job title!");

  demoOutput.classList.add("visible");
  showLoader(true);
  results.style.display = "none";
  generateBtn.disabled = true;
  generateBtn.textContent = "Generating...";

  try {
    const res = await fetch(API_URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ job_title: job })
    });

    const data = await res.json();
    console.log("RAW API RESPONSE:", data);

    let parsed;
    try {
      parsed = JSON.parse(data.ai_text.replace(/```json|```/g, "").trim());
    } catch {
      console.warn("Could not parse AI JSON — using fallback sample.");
      parsed = {
        skills: [
          "Python Programming",
          "SQL",
          "Machine Learning",
          "Statistics",
          "Data Visualization",
          "Deep Learning",
          "Pandas & NumPy",
          "MLOps Basics",
          "APIs & Cloud",
          "Communication"
        ],
        courses: [
          { title: "Python for Everybody", url: "https://www.coursera.org/specializations/python" },
          { title: "Intro to Machine Learning", url: "https://www.kaggle.com/learn/intro-to-machine-learning" }
        ],
        duration_months: 6,
        avg_salary_usd: "$90,000 - $130,000"
      };
    }

    populateResults(parsed, job);
  } catch (err) {
    console.error("Request failed:", err);
    alert("Error connecting to backend");
  } finally {
    showLoader(false);
    generateBtn.disabled = false;
    generateBtn.textContent = "Generate My Roadmap";
  }
}

function populateResults(data, job) {
  results.style.display = "block";
  skillsGrid.innerHTML = "";
  courseList.innerHTML = "";

  (data.skills || []).forEach((s) => {
    const chip = document.createElement("div");
    chip.className = "skill-chip";
    chip.textContent = s;
    skillsGrid.appendChild(chip);
  });

  (data.courses || []).forEach((c) => {
    const item = document.createElement("div");
    item.className = "course-item";
    item.innerHTML = `<a href="${c.url}" target="_blank">${c.title}</a>`;
    courseList.appendChild(item);
  });

  durationValue.textContent = data.duration_months + " months";
  salaryValue.textContent = data.avg_salary_usd;

  console.log("Rendered:", data);
}

generateBtn.addEventListener("click", generateRoadmap);
jobInput.addEventListener("keypress", (e) => {
  if (e.key === "Enter") generateRoadmap();
});

generateStarfield();

// === Download as TXT ===
function downloadRoadmap(job, data) {
  const content = `
PathFinder AI - Career Roadmap
==============================

Role: ${job}

Top 10 Skills:
${(data.skills || []).map((s, i) => `${i + 1}. ${s}`).join("\n")}

Recommended Courses:
${(data.courses || [])
    .map((c, i) => `${i + 1}. ${c.title}\n   ${c.url}`)
    .join("\n\n")}

Duration: ${data.duration_months || "N/A"} months
Average Salary: ${data.avg_salary_usd || "N/A"}

Generated by PathFinder AI
  `.trim();

  const blob = new Blob([content], { type: "text/plain" });
  const link = document.createElement("a");
  link.href = URL.createObjectURL(blob);
  link.download = `${job.replace(/\s+/g, "_")}_Roadmap.txt`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(link.href);
}

// Connect the download button dynamically after results load
downloadBtn.addEventListener("click", () => {
  const job = jobInput.value.trim() || "Career_Roadmap";
  const skills = Array.from(document.querySelectorAll("#skillsGrid .skill-chip")).map((el) => el.textContent);
  const courses = Array.from(document.querySelectorAll("#courseList a")).map((el) => ({
    title: el.textContent,
    url: el.href
  }));

  const data = {
    skills,
    courses,
    duration_months: durationValue.textContent.replace(" months", ""),
    avg_salary_usd: salaryValue.textContent
  };

  downloadRoadmap(job, data);
});
